
import PostSearch from "@/components/PostSearch";
import Posts from "@/components/Posts";
import { getAllPosts } from "@/services/getPosts";

import { Metadata } from "next"
import Link from "next/link";
import { useEffect, useState } from "react";


// async function getData() {
//     const response = await fetch('https://jsonplaceholder.typicode.com/posts');
//     next: {
//         revalidate: 60
//     }
//     if (!response.ok) throw new Error('unable to fetch data');

//     return response.json();
// }


export const metadata: Metadata = {
    title: 'Blog | Next App',
    description: 'Generated by create next app',
}

export default function Blog () {
    // const posts = await getData();
    // const [posts, setPosts] = useState<any[]>([]);
    // const [loading, setLoading] = useState(false);

    // useEffect(() => {
    //     getAllPosts()
    //         .then(setPosts)
    //         .finally(() => setLoading(false));
    // }, [])


    return (
        <>
            <h1>Blog Page</h1>
            {/* <PostSearch onSearch={setPosts}/> */}
            <PostSearch />
           
                <Posts />
          
        
        </>
    ) 
    
}